print('What is your name?')
name = input()
print('It is food, nuce to meet you, ' + name.title() + '!')
print('The lenght of your name is: ')
print(len(name))
print('What is your age?')
age = input()
print('You will be ' + str(int(age)+1) + ' in a year.')